### ISSUE TITLE
copt: deleted label inappropriately

### ISSUE THREAD

**Issue by Deek** [Deek/CoCoC#1]
When compiling a particular C file, the optimizer turned this:

```
_42
 clra
 clrb
 pshs d
 clra
 clrb
 pshs d
 pshs d
```
into this:
```
 clra
 clrb
 pshs d
 pshs d
 pshs d
```
 
The code itself is correct, but it deleted the "_42" label in the process. That's wrong, and keeps the code from linking.

**Comment by debmint** [comment]
Did you get this fixed? I know where this problem is.  When it parses a label, it only accepts alnum chars.  it translates "t_first" into "t".  I can fix this if you haven't already done so.

**Comment by Deek** [comment]
Numeric labels work, this is a very specific case. Our version of the optimizer is able to move labels from one instruction to another (but only in ways that don't cause code to be executed when it shouldn't be).

The correct thing would be to move the `_42` label to the first `clra` instruction in the chunk, but that section is reasonably complex; it's basically just a 3-coffee problem. 😃

**Comment by debmint** [comment]
I see.  The reason I asked was that when I was getting c3optx to work it was parsing only for alnum() chars, and when an underscore was encountered, it cut off the underscore and anything following.  But when I checked your code, this did not happen.  Either this was something introduced in the "exp" branch or you fixed it.

**Comment by Deek** [comment]
I remember that bug, it has to do with the unusual way the optimizer uses the RMA charset rather than C's (but doesn't change the macros). If you use the C charset, it doesn't consider _ an alphanumeric char, but with the RMA charset it does.
